#!/bin/bash

coproc wttr {
	while :
	do
		export WTTR="$(curl -s wttr.in?format=3)"
		echo hey $WTTR
		sleep 10m
	done
}


# while :
# do
# 	local a b c cpu idle total rest
# 	read -r cpu a b c idle rest </proc/stat
# 	total=$((a + b + c))
# 
# 	export CPU="$(printf '%.1f\n' $((100 * total / (total + idle))))"
# 	sleep 15
# done &
# 
# while :
# do
# 	export MEM="$(free -m | awk '/^Mem/ {print $7}')"
# 	sleep 20
# done &

while :
do
	sleep 10
	xsetroot -name "$WTTR | CPU[$CPU%] | RAM[$MEM MiB] | $(date) "
done
